# Generated by Django 5.2.5 on 2025-10-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(db_column='названиеМатериала', max_length=255, verbose_name='Material Name')),
                ('color_code', models.CharField(db_column='артикулЦвета', max_length=100, verbose_name='Color Code')),
                ('supplier_id', models.IntegerField(db_column='поставщик', verbose_name='Supplier ID')),
                ('cost', models.DecimalField(db_column='стоимостьЗаЕдиницу', decimal_places=2, max_digits=10, verbose_name='Cost per Unit')),
                ('note', models.TextField(blank=True, db_column='описание', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Image URL')),
            ],
            options={
                'verbose_name': 'Камень',
                'verbose_name_plural': 'Камни',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_column='названиеКомпании', max_length=255, verbose_name='Company Name')),
                ('contact_person', models.CharField(db_column='контактноеЛицо', max_length=255, verbose_name='Contact Person')),
                ('email', models.EmailField(db_column='электроннаяПочта', max_length=254, verbose_name='Email')),
                ('supplier_address', models.TextField(db_column='адресПоставщика', verbose_name='Supplier Address')),
                ('phone', models.CharField(db_column='телефон', max_length=50, verbose_name='Phone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('note', models.TextField(blank=True, db_column='примечание', null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
    ]
