# Generated by Django 5.2.5 on 2025-10-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_column='ФИО', max_length=255, verbose_name='Full Name')),
                ('contact_phone', models.CharField(db_column='Контактный телефон', max_length=50, verbose_name='Contact Phone')),
                ('email', models.EmailField(db_column='электронная почта', max_length=254, verbose_name='Email')),
                ('address', models.TextField(db_column='адрес', verbose_name='Address')),
                ('note', models.TextField(blank=True, db_column='примечание', null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
