# Generated by Django 5.2.5 on 2025-10-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(db_column='id_клиент', verbose_name='Client ID')),
                ('calculation_id', models.IntegerField(blank=True, db_column='id_расчета', null=True, verbose_name='Calculation ID')),
                ('total_amount', models.DecimalField(db_column='сумма_заказа', decimal_places=2, max_digits=12, verbose_name='Total Amount')),
                ('material_id', models.IntegerField(db_column='id_материал', verbose_name='Material ID')),
                ('employee_id', models.IntegerField(blank=True, db_column='id_сотрудника', null=True, verbose_name='Employee ID')),
                ('material_quantity', models.DecimalField(db_column='количество_материала', decimal_places=3, default=0.0, max_digits=10, verbose_name='Material Quantity')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('calculation_confirmed', 'Расчет подтвержден'), ('awaiting_advance', 'Ожидает аванса'), ('in_production', 'В производстве'), ('ready_for_installation', 'Готов к установке'), ('awaiting_installation', 'Ожидает установки'), ('installation', 'Установка'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], db_column='статус_заказа', default='new', max_length=50, verbose_name='Status')),
                ('advance_payment_amount', models.DecimalField(blank=True, db_column='сумма_аванса', decimal_places=2, max_digits=12, null=True, verbose_name='Advance Payment Amount')),
                ('advance_payment_date', models.DateTimeField(blank=True, db_column='дата_внесения_аванса', null=True, verbose_name='Advance Payment Date')),
                ('installation_date', models.DateTimeField(blank=True, db_column='дата_установки', null=True, verbose_name='Installation Date')),
                ('needs_installation', models.BooleanField(db_column='установка', default=False, verbose_name='Needs Installation')),
                ('needs_delivery', models.BooleanField(db_column='доставка', default=False, verbose_name='Needs Delivery')),
                ('order_number', models.CharField(blank=True, db_column='orderNumber', max_length=50, null=True, unique=True, verbose_name='Order Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('order_date', models.DateField(db_column='дата_заказа', verbose_name='Order Date')),
                ('note', models.TextField(blank=True, db_column='примечание', null=True, verbose_name='Note')),
                ('advance_payment_type', models.CharField(blank=True, choices=[('cash', 'Наличные'), ('cashless', 'Безналичные')], max_length=50, null=True, verbose_name='Advance Payment Type')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='Order ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Price')),
            ],
            options={
                'verbose_name': 'Позиция в заказе',
                'verbose_name_plural': 'Позиции в заказе',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='Order ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта'), ('bank_transfer', 'Банковский перевод'), ('online', 'Онлайн-платеж'), ('credit', 'Кредит'), ('installment', 'Рассрочка')], max_length=20, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('completed', 'Успешно завершен'), ('failed', 'Неудачный платеж'), ('refunded', 'Возврат средств'), ('partially_refunded', 'Частичный возврат')], default='pending', max_length=20, verbose_name='Status')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_by_id', models.IntegerField(blank=True, null=True, verbose_name='Created By')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
