# Generated by Django 5.2.5 on 2025-10-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(verbose_name='Owner ID')),
                ('pricelist_id', models.IntegerField(verbose_name='Pricelist ID')),
                ('name', models.CharField(max_length=255, verbose_name='Calculation Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Расчет',
                'verbose_name_plural': 'Расчеты',
            },
        ),
        migrations.CreateModel(
            name='CalculationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_id', models.IntegerField(verbose_name='Calculation ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='Item Name')),
                ('unit', models.CharField(max_length=50, verbose_name='Unit')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price')),
                ('total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Позиция расчета',
                'verbose_name_plural': 'Позиции расчета',
            },
        ),
    ]
