# Generated by Django 5.2.5 on 2025-10-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.IntegerField(verbose_name='ID материала')),
                ('order_id', models.IntegerField(blank=True, null=True, verbose_name='ID клиентского заказа')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Закупленное количество')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общая стоимость закупки')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта'), ('bank_transfer', 'Банковский перевод'), ('online', 'Онлайн-платеж'), ('credit', 'Кредит'), ('installment', 'Рассрочка')], default='cash', max_length=20, verbose_name='Способ оплаты поставщику')),
                ('purchase_order_date', models.DateField(verbose_name='Дата заказа у поставщика')),
                ('status', models.CharField(max_length=20, verbose_name='Статус получения')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Дата получения от поставщика')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечание к закупке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
            ],
            options={
                'verbose_name': 'Закупка материала',
                'verbose_name_plural': 'Закупки материалов',
                'ordering': ['-purchase_order_date', '-created_at'],
            },
        ),
    ]
